server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:validate}
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DB_CONNECTION:jdbc:mysql://localhost:3307/point}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
